
title = "Jones' Barber Shop"
theme = "hugo-barber"
languageCode = "en-us"

# Enable Google Analytics by entering your tracking code
# googleAnalytics = ""

[related]
threshold = 50
includeNewer = true
toLower = true

[[related.indices]]
name = "tags"
weight = 100

[params]
  description = "Jones' Barber Shop"
  copyright = "&copy;2019 Jones' Barber Shop"
  about = [
    "If you’re looking for fun conversation with a great atmosphere, look no further!"
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "JonesBarberShop@icloud.com"

menu:
  main:
  - identifier: about
    name: about hugo
    pre: <i class='fa fa-heart'></i>
    url: /about/
    weight: -110
  - name: getting started
    post: <span class='alert'>New!</span>
    pre: <i class='fa fa-road'></i>
    url: /getting-started/
    weight: -100
 

  [params.social]
  facebook      = "https://www.facebook.com/pg/JonesBarberShop317"
#  googleplus    = "full profile url in googleplus"
  email         = "mailto:chad.b.jones2380@icloud.com"
#  twitter       = "full profile url in twitter"
#  linkedin      = "full profile url in linkedin"
  instagram     = "https://instagram.com/theotherchadthebarber"
#  youtube       = "full profile url in youtube"
#  whatsapp      = "wa.me service link"
