languageCode = "en-us"
theme = "hugo-barber"
title = "Jones' Barber Shop"
[[menu.main]]
name = "PHOTOS"
url = "/portfolio/"
weight = 1
[[menu.main]]
name = "SERVICES"
post = "<span class='alert'>New!</span>"
pre = "<i class='fa fa-road'></i>"
url = "/services/"
weight = 3
[[menu.main]]
identifier = "about"
name = "BARBERS"
pre = "<i class='fa fa-heart'></i>"
url = "/BARBERS/"
weight = 2
[params]
about = ["If you’re looking for fun conversation with a great atmosphere, look no further!"]
copyright = "&copy;2019 Jones' Barber Shop"
description = "Jones' Barber Shop"
email = "JonesBarberShop@icloud.com"
[params.social]
email = "mailto:chad.b.jones2380@icloud.com"
facebook = "https://www.facebook.com/pg/JonesBarberShop317"
instagram = "https://instagram.com/theotherchadthebarber"
[related]
includeNewer = true
threshold = 50
toLower = true
[[related.indices]]
name = "tags"
weight = 100
