---
label: Service
hide_body: false
is_partial: false
fields:
- type: text
  name: title
  label: Service
- type: text
  name: duration
  label: Duration
- type: text
  name: price
  label: Price
- type: file
  name: image
  label: Example
pages:
- content/services/undercut-design.md
- content/services/line-up.md
- content/services/beard-trim.md
- content/services/shave.md
- content/services/men-s-haircut.md
- content/services/design.md
- content/services/young-man-s-haircut.md
